MAIN_WINDOW_TITLE = 'Talzeeq'

FILE_MENU_NAME = '&File'

EDIT_MENU_NAME = '&Edit'

FRAMEWORKS_TOOLBAR_NAME = 'Frameworks'

POINTER_TYPE_TOOLBAR_NAME = 'Pointer type'

DIAGRAM_EDIT_TOOLBAR_NAME = 'Diagram Edit'

FRAMEWORKS_LABEL = 'Framework: '

DIAGRAM_SCENE_SIZE = 5000

DIAGRAM_SCENE_SCALES = ['50%', '75%', '100%', '125%', '150%']

DIAGRAM_SCENE_DEFAULT_SCALE = '100%'

DIAGRAM_SCENE_SCALE_PERCENT = '%'

LAYERS = 'Layers'
