# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/frameworks/Keras/designs/input_layer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputLayer(object):
    def setupUi(self, InputLayer):
        InputLayer.setObjectName("InputLayer")
        InputLayer.resize(400, 74)
        self.formLayout = QtWidgets.QFormLayout(InputLayer)
        self.formLayout.setObjectName("formLayout")
        self.objectNameLabel = QtWidgets.QLabel(InputLayer)
        self.objectNameLabel.setObjectName("objectNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.objectNameLabel)
        self.objectNameLineEdit = QtWidgets.QLineEdit(InputLayer)
        self.objectNameLineEdit.setObjectName("objectNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.objectNameLineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(InputLayer)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(InputLayer)
        self.buttonBox.accepted.connect(InputLayer.accept)
        self.buttonBox.rejected.connect(InputLayer.reject)
        QtCore.QMetaObject.connectSlotsByName(InputLayer)

    def retranslateUi(self, InputLayer):
        _translate = QtCore.QCoreApplication.translate
        InputLayer.setWindowTitle(_translate("InputLayer", "Input Layer"))
        self.objectNameLabel.setText(_translate("InputLayer", "Object Name"))
